// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: proto/calc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arg1          float32                `protobuf:"fixed32,1,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2          float32                `protobuf:"fixed32,2,opt,name=arg2,proto3" json:"arg2,omitempty"`
	Opr           string                 `protobuf:"bytes,3,opt,name=opr,proto3" json:"opr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_calc_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetArg1() float32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *TaskRequest) GetArg2() float32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *TaskRequest) GetOpr() string {
	if x != nil {
		return x.Opr
	}
	return ""
}

type ResResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           float32                `protobuf:"fixed32,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResResponse) Reset() {
	*x = ResResponse{}
	mi := &file_proto_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResResponse) ProtoMessage() {}

func (x *ResResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResResponse.ProtoReflect.Descriptor instead.
func (*ResResponse) Descriptor() ([]byte, []int) {
	return file_proto_calc_proto_rawDescGZIP(), []int{1}
}

func (x *ResResponse) GetRes() float32 {
	if x != nil {
		return x.Res
	}
	return 0
}

var File_proto_calc_proto protoreflect.FileDescriptor

const file_proto_calc_proto_rawDesc = "" +
	"\n" +
	"\x10proto/calc.proto\x12\x04calc\"G\n" +
	"\vTaskRequest\x12\x12\n" +
	"\x04arg1\x18\x01 \x01(\x02R\x04arg1\x12\x12\n" +
	"\x04arg2\x18\x02 \x01(\x02R\x04arg2\x12\x10\n" +
	"\x03opr\x18\x03 \x01(\tR\x03opr\"\x1f\n" +
	"\vResResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x02R\x03res2B\n" +
	"\vCalcService\x123\n" +
	"\vCalculation\x12\x11.calc.TaskRequest\x1a\x11.calc.ResResponseB+Z)github.com/ArtemiySps/calc_go_final/protob\x06proto3"

var (
	file_proto_calc_proto_rawDescOnce sync.Once
	file_proto_calc_proto_rawDescData []byte
)

func file_proto_calc_proto_rawDescGZIP() []byte {
	file_proto_calc_proto_rawDescOnce.Do(func() {
		file_proto_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calc_proto_rawDesc), len(file_proto_calc_proto_rawDesc)))
	})
	return file_proto_calc_proto_rawDescData
}

var file_proto_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_calc_proto_goTypes = []any{
	(*TaskRequest)(nil), // 0: calc.TaskRequest
	(*ResResponse)(nil), // 1: calc.ResResponse
}
var file_proto_calc_proto_depIdxs = []int32{
	0, // 0: calc.CalcService.Calculation:input_type -> calc.TaskRequest
	1, // 1: calc.CalcService.Calculation:output_type -> calc.ResResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_calc_proto_init() }
func file_proto_calc_proto_init() {
	if File_proto_calc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calc_proto_rawDesc), len(file_proto_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calc_proto_goTypes,
		DependencyIndexes: file_proto_calc_proto_depIdxs,
		MessageInfos:      file_proto_calc_proto_msgTypes,
	}.Build()
	File_proto_calc_proto = out.File
	file_proto_calc_proto_goTypes = nil
	file_proto_calc_proto_depIdxs = nil
}
